/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.Mihiri.FoodShopMangementSystem.views;

import lk.Mihiri.FoodShopMangementSystem.controller.CustomerFormController;
import lk.Mihiri.FoodShopMangementSystem.dto.CustomerDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import lk.Mihiri.FoodShopMangementSystem.entity.Customer;

/**
 *
 * @author navis
 */
public class CustomerFrom extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrom
     */
    public CustomerFrom() {
        initComponents();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCusID = new javax.swing.JTextField();
        txtCusAddess = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCusContact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        Searchtable = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Customer ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        txtCusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 240, 33));

        txtCusAddess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusAddessActionPerformed(evt);
            }
        });
        getContentPane().add(txtCusAddess, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Contact Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, -1));

        txtCusContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusContactActionPerformed(evt);
            }
        });
        getContentPane().add(txtCusContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customer Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, -1, -1));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", " Name", "Contact Number", "Address"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 431, -1, 142));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 304, 140, 40));

        btnRegister.setBackground(new java.awt.Color(102, 102, 102));
        btnRegister.setText("Register Customer");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 91, 140, 44));

        btnEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnEdit.setText("Edit Customer");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 40));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setText("Remove Customer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 234, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Customer Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        txtCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, 240, 33));

        Searchtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchtableKeyReleased(evt);
            }
        });
        getContentPane().add(Searchtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Search");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, -1, -1));

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Manage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 588, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusIDActionPerformed

    private void txtCusAddessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusAddessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusAddessActionPerformed

    private void txtCusContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusContactActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      
        clearAllText();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        
        String customerID=txtCusID.getText();
        String customerName = txtCusName.getText();
        String phoneNumber=txtCusContact.getText();
        String customerAddres = txtCusAddess.getText();
        

        CustomerDTO customerDTO= new CustomerDTO(customerID,customerName, phoneNumber, customerAddres);
        
        try {
            boolean addCustomer =new CustomerFormController().addCustomer(customerDTO);
            if (addCustomer) {
                JOptionPane.showMessageDialog(this, "Customer Registerd..!");
                loadAllCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Registerd..!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       
        String customerID=txtCusID.getText();
        String customerName = txtCusName.getText();
        String phoneNumber=txtCusContact.getText();
        String customerAddres = txtCusAddess.getText();
        
          CustomerDTO Updatecustomer= new CustomerDTO(customerID,customerName, phoneNumber, customerAddres);
            
          boolean result;
        try {
            result = new CustomerFormController().updateCustomer(Updatecustomer);
            if (result) {
                JOptionPane.showMessageDialog(this, "Customer Updated..!");
                loadAllCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Updated..!");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
        
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         String customerID = txtCusID.getText();

      
            boolean result;
        try {
            result = new CustomerFormController().removeCustomer(customerID);
            if (result) {
                JOptionPane.showMessageDialog(this, "Customer Removed..!");
                loadAllCustomers();
                clearAllText();
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Removed..!");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusNameActionPerformed

    private void SearchtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchtableKeyReleased
       
        DefaultTableModel table=(DefaultTableModel)tblCustomer.getModel();
        String Search =Searchtable.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        tblCustomer.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Search));
        
    }//GEN-LAST:event_SearchtableKeyReleased

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        
        int selecedRow=tblCustomer.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) tblCustomer.getModel();
        
        txtCusID.setText(model.getValueAt(selecedRow, 0).toString());
        txtCusName.setText(model.getValueAt(selecedRow, 1).toString());
        txtCusContact.setText(model.getValueAt(selecedRow, 2).toString());
        txtCusAddess.setText(model.getValueAt(selecedRow, 3).toString());
      
        
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      
        dispose();
        DashBord dashBord =new DashBord();
        dashBord.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Searchtable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtCusAddess;
    private javax.swing.JTextField txtCusContact;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    // End of variables declaration//GEN-END:variables

 private void clearAllText() {
        txtCusID.setText("");
        txtCusName.setText("");
        txtCusContact.setText("");
        txtCusAddess.setText("");
        txtCusID.requestFocus();
        loadAllCustomers();
    }    
    
    
private void loadAllCustomers() {

        DefaultTableModel dtm = (DefaultTableModel) tblCustomer.getModel();
        //dtm.setRowCount(0);

        
            ArrayList<CustomerDTO> allCustomers;
        try {
            allCustomers = new CustomerFormController().getAllCustomers();
            for (CustomerDTO customerDTO : allCustomers) {

                Object[] row = {customerDTO.getCustomerID(), customerDTO.getCustomerName(), customerDTO.getCustomerContacts(), customerDTO.getCustomerAddress()};
                dtm.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
            

       
    }

}
